// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImv9JOY5qx3CjIOR9F32QIoVTQ1Ozdvc',
    appId: '1:16662598921:web:a8c9dd9cc08341a2236fd8',
    messagingSenderId: '16662598921',
    projectId: 'super-youth',
    authDomain: 'super-youth.firebaseapp.com',
    storageBucket: 'super-youth.firebasestorage.app',
    measurementId: 'G-V22ZKF2EE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgsgsOsZk9P-qqVqOUsny7BVLzL2J5-uI',
    appId: '1:16662598921:android:f375afe9b136ff39236fd8',
    messagingSenderId: '16662598921',
    projectId: 'super-youth',
    storageBucket: 'super-youth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu5wgn32xtSVqrtNOII-ZGJ0TtgW4piuo',
    appId: '1:16662598921:ios:ef005e511776f71b236fd8',
    messagingSenderId: '16662598921',
    projectId: 'super-youth',
    storageBucket: 'super-youth.firebasestorage.app',
    iosBundleId: 'com.example.superYouth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu5wgn32xtSVqrtNOII-ZGJ0TtgW4piuo',
    appId: '1:16662598921:ios:ef005e511776f71b236fd8',
    messagingSenderId: '16662598921',
    projectId: 'super-youth',
    storageBucket: 'super-youth.firebasestorage.app',
    iosBundleId: 'com.example.superYouth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAImv9JOY5qx3CjIOR9F32QIoVTQ1Ozdvc',
    appId: '1:16662598921:web:0677cd7380be2c4a236fd8',
    messagingSenderId: '16662598921',
    projectId: 'super-youth',
    authDomain: 'super-youth.firebaseapp.com',
    storageBucket: 'super-youth.firebasestorage.app',
    measurementId: 'G-44Y5DGTN59',
  );

}